global:
  scrape_interval: 10s

scrape_configs:
  - job_name: order-api
    static_configs:
      - targets: ["order-api:8080"]
    metrics_path: /metrics

  - job_name: outbox-publisher
    static_configs:
      - targets: ["outbox-publisher:8080"]
    metrics_path: /metrics

  - job_name: risk-engine
    static_configs:
      - targets: ["risk-engine:8080"]
    metrics_path: /metrics

  - job_name: limit-service
    static_configs:
      - targets: ["limit-service:8080"]
    metrics_path: /metrics

  - job_name: notification-worker
    static_configs:
      - targets: ["notification-worker:8080"]
    metrics_path: /metrics
